<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Toyota</name>
   <tag></tag>
   <isRerun>false</isRerun>
<<<<<<< HEAD
   <lastRun>2018-09-20T11:01:24</lastRun>
=======
   <lastRun>2018-09-19T15:46:13</lastRun>
>>>>>>> branch 'master' of https://github.com/nhiendohao/TitanAPIKatalon
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>980cb084-1f5c-4b65-9896-07df0294a147</testSuiteGuid>
   <testCaseLink>
      <guid>fa7f052e-4d16-4609-9d7d-6d0578a72c8c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Setup_Method_And_Variables</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d45f24d2-cd39-4d32-adfa-141cc3b8666f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e2571972-45cb-4465-9d32-7fd0207a1887</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>92b95cb1-e8c2-4924-8ceb-ea013c4af26f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fc2f80e8-5582-4a58-a31d-c409035678fd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>325316ed-93d4-49f0-98b9-e2b87b67a58b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Toyota_GetPickUpTimes_JSON</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>596b13c0-d988-43d1-b934-eaab4e6346fe</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
