<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Toyota</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-09-19T15:46:13</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>980cb084-1f5c-4b65-9896-07df0294a147</testSuiteGuid>
   <testCaseLink>
      <guid>1383de23-b212-467a-a41f-156bc0fa8e2f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Toyota_GetDropOffTimes_JSON</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>98b2d172-ce16-45c7-a76c-a91fdd9d8b46</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f61dbbc2-8d93-40ef-b22c-7d88bca1c819</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ed347226-1e3e-487a-b472-5f5c37903915</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9631be46-52e2-418f-b90a-a2a6ea89eaa7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Toyota_GetServiceOperation</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
