<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Toyota</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-09-20T11:31:16</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>66c5312a-8b69-48c4-bb8e-40543670b6ee</testSuiteGuid>
   <testCaseLink>
      <guid>3ec44f68-210c-4314-b146-176d9f2e0108</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Setup_Method_And_Variables</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d45f24d2-cd39-4d32-adfa-141cc3b8666f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e2571972-45cb-4465-9d32-7fd0207a1887</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>92b95cb1-e8c2-4924-8ceb-ea013c4af26f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fc2f80e8-5582-4a58-a31d-c409035678fd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>da62ce0e-41bc-4394-aba2-ba9de96005c7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Toyota_GetDropOffTimes_JSON</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>98b2d172-ce16-45c7-a76c-a91fdd9d8b46</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f61dbbc2-8d93-40ef-b22c-7d88bca1c819</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ed347226-1e3e-487a-b472-5f5c37903915</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bfcc9eb3-e899-402c-9911-0cf8301f7b8a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Toyota_GetPickUpTimes_JSON</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>596b13c0-d988-43d1-b934-eaab4e6346fe</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
